const fs = require('fs');
const path = require('path');

const storyPath = path.join('d:', 'Farhan-project', 'eclipse', 'story.json');

try {
  const content = fs.readFileSync(storyPath, 'utf8');
  const data = JSON.parse(content);
  
  if (data.chapters && data.chapters[0].chapter_id === 1) {
    const sub_chapters = data.chapters[0].sub_chapters;

    const sub0 = [
        "Di Ambervile, desa kecil yang nyaris terlupakan oleh peta dunia, malam selalu datang lebih cepat dari seharusnya. Kabut turun seperti tirai rahasia, menelan suara dan kenangan. Di balik pintu kayu tua yang berderit, sebuah bar sederhana berdiri—tempat para pengelana mengubur cerita mereka dalam gelas-gelas murahan. Di sanalah aku berdiri, seperti bayangan yang tak pernah benar-benar pergi.",
        "Namaku Frentzie. Orang-orang mengenalku sebagai bartender. Pendengar yang baik. Tangan yang cekatan meracik minuman, dan senyum yang cukup untuk membuat seseorang lupa sejenak pada dunia luar. Tapi mereka tidak pernah tahu… bahwa aku juga menghitung napas mereka, memperhatikan denyut nadi mereka, dan melihat sesuatu yang tak bisa dilihat orang biasa.",
        "Darah. Bukan sekadar darah biasa—melainkan jejak sumpah kuno yang mengalir di dalamnya. Vowbearer. Aku bisa melihat mereka. Entah sebagai kilatan samar di mata, atau rasa dingin yang merayap di tulang. Mereka yang membawa sisa-sisa “Eclipse Vow”—sebuah peristiwa yang bahkan kerajaan pun berpura-pura tidak pernah terjadi.",
        "Keluargaku… adalah bagian dari itu. Dan mereka dibunuh karenanya. Malam itu masih terukir jelas dalam pikiranku. Api yang melahap rumah, teriakan yang dipaksa diam oleh pedang, dan lambang kerajaan yang berkilau dingin di tengah kegelapan. Tidak ada pengadilan. Tidak ada penjelasan. Hanya satu tuduhan: “Orang sesat.”",
        "Aku selamat… bukan karena keberanian, tapi karena kebetulan yang terasa seperti kutukan. Sejak hari itu, aku tidak lagi hanya anak dari seorang bartender… atau putra seorang petualang. Aku menjadi sesuatu yang lain. Penyintas. Pembawa pertanyaan yang tidak memiliki jawaban.",
        "Aku mewarisi bar ini dari kakekku—tempat di mana orang-orang datang dan pergi tanpa nama. Tempat yang sempurna untuk mengamati. Untuk mencari. Untuk menunggu. Karena satu per satu, mereka mulai muncul. Orang-orang dengan tatapan kosong yang terlalu dalam. Pengelana yang membawa luka yang tak terlihat. Mereka yang tanpa sadar menyimpan serpihan dari sumpah yang telah dihancurkan. Vowbearer… seperti diriku.",
        "Dan aku mengumpulkan mereka. Bukan sebagai pahlawan. Bukan sebagai penyelamat. Tapi sebagai pecahan dari sesuatu yang lebih besar—sesuatu yang dunia ini berusaha keras untuk kubur.",
        "Aku tidak mencari keadilan. Aku mencari kebenaran. Tentang “Eclipse Vow.” Tentang kerajaan yang membantai tanpa ragu. Tentang dunia yang tampaknya berdiri di atas kebohongan yang terlalu lama dipercaya. Dan semakin dalam aku menggali… semakin aku menyadari bahwa ini bukan hanya tentang manusia, atau kerajaan, atau kekuasaan.",
        "Ini tentang sesuatu yang lebih tua. Lebih gelap. Lebih… ilahi. Seperti yang tertulis dalam artefak kuno yang kini kusimpan di balik lantai kayu bar ini—teks yang bahkan para pendeta takut untuk membacanya dengan suara keras: “Apakah Tuhan menciptakan manusia… atau manusia yang menciptakan Tuhan?”",
        "Aku belum tahu jawabannya. Tapi jika kebenaran itu memang ada—aku akan menemukannya. Bahkan jika aku harus menghancurkan dunia ini untuk melakukannya."
    ];

    const sub1 = [
        "Mereka lahir di dunia yang bahkan belum sempat membenci mereka—karena sejak awal, dunia itu sudah menolak keberadaan mereka. Dua anak kembar berambut hijau. Steffy… dan Yuffie. Sebuah tanda dari hubungan terlarang antara bangsawan dan pembantunya. Sebuah noda yang harus dihapus, bahkan sebelum sempat diberi arti.",
        "Steffy lahir lima menit lebih dulu. Sebuah selisih waktu yang kecil… namun cukup untuk membuatnya tanpa sadar selalu berdiri di depan. Di depan bahaya. Di depan luka. Di depan dunia.",
        "Namun takdir, yang sering kali kejam, kadang menyisakan serpihan belas kasih yang nyaris tak terlihat. Mereka ditemukan oleh seorang nenek tua di sudut kota yang terlupakan. Perempuan renta yang tidak memiliki apa-apa… kecuali hati yang terlalu besar untuk dunia yang terlalu kecil. Di bawah atap rapuh dan dinding yang nyaris runtuh, mereka untuk pertama kalinya mengenal sesuatu yang asing. Hangat. Tangan yang membelai tanpa menolak. Suara yang memanggil tanpa menghakimi. Dan untuk sesaat… dunia terasa tidak sepenuhnya salah.",
        "Namun kebahagiaan, di dunia seperti ini, tidak pernah datang tanpa batas waktu. Saat usia mereka menginjak tujuh tahun, tubuh sang nenek mulai menyerah. Tidak ada tabib. Tidak ada keajaiban. Hanya napas yang semakin pendek… dan keheningan yang akhirnya menetap. Ia pergi. Dan bersama kepergiannya… dunia kembali menunjukkan wajah aslinya.",
        "Sejak hari itu, Steffy berubah. Ia berhenti menjadi anak-anak. Ia belajar mencuri sebelum ia memahami benar dan salah. Ia belajar berbohong sebelum ia mengenal kepercayaan. Ia belajar bertarung sebelum ia mengerti arti hidup. Setiap luka… ia simpan. Setiap rasa sakit… ia telan. Karena ada satu hal yang tidak boleh hancur. Yuffie.",
        "Sementara itu, Yuffie… memilih jalan yang berbeda. Jika Steffy menjadi badai yang membekukan—Maka Yuffie menjadi badai kecil yang hangat. Ia tertawa di tengah kelaparan. Ia tersenyum di tengah penghinaan. Di mata dunia, ia hanyalah gadis berisik yang tidak serius. Namun itu adalah pilihannya. Karena orang yang diremehkan… tidak pernah dianggap ancaman. Dan itu membuatnya bebas. Bebas untuk mengamati. Bebas untuk bertahan. Bebas untuk melindungi.",
        "Karena diam-diam, Yuffie juga bertarung. Ia sengaja kalah dalam perkelahian. Ia sengaja terlihat lemah. Namun setiap gerakannya… selalu berada di antara bahaya dan punggung Steffy. Jika bukan karena larangan kakaknya… dunia mungkin sudah melihat sisi lain dari dirinya. Sisi yang lebih tajam. Lebih berbahaya.",
        "Namun bagi Yuffie, semua itu tidak penting. Selama Steffy masih berdiri—Dunia ini masih layak untuk ditertawakan.",
        "Hari-hari berlalu dalam siklus yang sama. Mencuri. Menipu. Bertahan hidup. Hingga pada suatu malam… sesuatu berubah. Steffy sedang menjalankan “pekerjaan”-nya seperti biasa, kali ini dalam sebuah bar. Sebuah kebohongan yang sudah terlalu sering ia ulangi.",
        "Namun kali ini… targetnya tidak bereaksi seperti yang lain. Tidak marah. Tidak panik. Hanya diam. Dan menatap. Tatapan yang terasa… aneh. Seolah-olah bukan melihat wajahnya—Melainkan sesuatu yang mengalir di dalam dirinya. Darah.",
        "“Kalian berdua…” Suara itu tenang. Terlalu tenang untuk seseorang yang sedang ditipu. Steffy langsung tahu. Orang ini berbeda. Namun sebelum ia bisa mundur—Yuffie sudah berada di sampingnya. Seperti biasa. Tanpa suara. Tanpa ragu. Melindungi.",
        "Pria itu tersenyum tipis. Bukan senyum ramah. Melainkan senyum seseorang yang akhirnya menemukan sesuatu yang telah lama ia cari. Ia berhenti sejenak. Seolah memastikan sesuatu. “Vowbearer?”",
        "Kata itu menggema. Bukan di telinga. Tapi di dalam darah. Steffy merasakan sesuatu bergerak. Sesuatu yang selama ini diam… kini terbangun. Sementara Yuffie—Ia hanya tersenyum. Namun untuk pertama kalinya… senyumnya tidak sepenuhnya main-main. Seperti ada bagian dari dirinya yang akhirnya menemukan arti.",
        "“Takdirmu bukan seperti ini,” lanjut pria itu. Langkahnya perlahan mendekat. Namun tidak mengancam. Tidak juga memaksa. “Ada sesuatu yang lebih besar dari dunia kecil ini. Sesuatu yang sedang menunggu kalian.”",
        "Steffy menggenggam tangan Yuffie. Refleks. Kebiasaan. Dan mungkin… ketakutan. Harapan… selalu terasa lebih berbahaya. “Siapa kau?” Akhirnya Steffy bertanya.",
        "Pria itu menatap mereka berdua. Untuk sesaat, suasana di sekitarnya terasa berbeda. Lebih berat. Seolah dunia itu sendiri menahan napas. Lalu ia menjawab. “Frentzie.”",
        "Seorang bartender… Seorang penyitas… Dan seseorang yang mencari kebenaran yang dunia ini coba kubur. Matanya kembali menatap mereka. Dalam. Dingin. Namun tidak sepenuhnya tanpa tujuan. “Jika kalian ingin tahu siapa…” Ia berbalik. “...ikut denganku.”",
        "Steffy terdiam. Dunia yang ia kenal mungkin kejam… Namun dunia yang tidak ia kenal… bisa jauh lebih buruk. Namun di sampingnya—Yuffie tertawa kecil. Seperti biasa. Ringan. Tanpa beban. “Kelihatannya seru.” Dan itu cukup.",
        "Steffy menghela napas pelan. Lalu melangkah. Bukan karena percaya. Bukan karena yakin. Namun karena ada satu hal yang ia pegang. Selama Yuffie ada di sisinya—Ia akan menghadapi apa pun. Bahkan jika itu adalah kebenaran yang bisa menghancurkan dunia.",
        "Dan di malam itu… Tanpa mereka sadari—Sebuah perjalanan telah dimulai. Perjalanan yang tidak hanya akan mengubah hidup mereka… Namun juga… nasib dunia itu sendiri."
    ];

    const sub2 = [
        "Arkaelia adalah desa yang tidak pernah benar-benar ada di mata dunia. Tersembunyi di antara lembah sunyi dan reruntuhan yang lebih tua dari ingatan manusia, tempat itu hidup dalam keheningan… seolah waktu sendiri enggan menyentuhnya.",
        "Di sanalah Franzsto dilahirkan. Bukan sebagai pejuang. Bukan sebagai penyintas. Melainkan sebagai seorang pencari. Sejak kecil, ia sudah berbeda. Saat anak-anak lain bermain, Franzsto berjalan menjauh—menyusuri sisa-sisa batu retak, menyentuh dinding kuno yang dipenuhi ukiran yang bahkan para tetua tidak mengerti.",
        "Ia tidak hanya melihat. Ia… mendengarkan. Seolah-olah masa lalu berbisik melalui celah-celah waktu. Dan entah bagaimana—ia mengerti. Bukan dalam bentuk kata. Tapi dalam rasa. Dalam bayangan. Dalam sesuatu yang tidak bisa dijelaskan.",
        "Namun Arkaelia menyimpan lebih dari sekadar sejarah. Ia menyimpan sesuatu yang seharusnya tidak pernah ditemukan. Hari itu datang tanpa pertanda. Sebuah artefak ditemukan… terkubur di bawah tanah yang bahkan tidak tercatat dalam peta lama. Tidak ada yang tahu siapa yang membuatnya. Tidak ada yang tahu untuk apa ia ada. Namun semua orang… merasakan sesuatu. Dingin. Seperti dunia menahan napas.",
        "Franzsto adalah orang pertama yang mendekat. Dan saat tangannya menyentuh permukaannya—Ia melihat. Bukan bayangan biasa. Bukan sekadar kilasan. Melainkan sesuatu yang utuh. Langit yang terbelah. Sumpah yang diucapkan dalam bahasa yang telah mati. Dan sesuatu… yang turun. Sesuatu yang tidak seharusnya ada di dunia manusia.",
        "Lalu artefak itu… merespons. Cahaya. Bukan cahaya yang hangat. Melainkan cahaya yang menghapus. Dalam sekejap—Arkaelia lenyap. Tidak terbakar. Tidak runtuh. Hilang. Seolah tidak pernah ada. Dan Franzsto… terbangun di tengah keheningan. Sendirian. Di antara puing yang tidak lagi memiliki arti.",
        "Sejak hari itu, ia tidak pernah benar-benar kembali menjadi manusia yang sama. Sesuatu di dalam dirinya… telah terbuka. Ia mulai merasakan hal-hal yang tidak bisa dijelaskan. Energi. Jejak. Sisa-sisa dari sesuatu yang pernah terjadi. Saat ia menyentuh benda… ia melihat masa lalunya. Saat ia menginjak tanah… ia mendengar gema yang tertinggal.",
        "Dunia, baginya, bukan lagi apa yang terlihat. Melainkan apa yang tersisa. Dan semua jejak itu… mengarah ke satu hal. Eclipse Vow. Sebuah nama yang muncul berulang kali. Dalam reruntuhan. Dalam bisikan. Dalam mimpi yang terasa terlalu nyata. Seolah-olah kehancuran Arkaelia… bukanlah kebetulan. Melainkan bagian dari sesuatu yang lebih besar.",
        "Sejak saat itu, Franzsto berjalan. Tanpa tujuan yang jelas… namun dengan arah yang pasti. Dari satu reruntuhan ke reruntuhan lain. Dari satu jejak ke jejak berikutnya. Ia tidak mencari jawaban. Ia mencari pola. Karena semakin dalam ia menggali—Semakin jelas satu hal. Ini bukan tentang masa lalu. Ini tentang sesuatu yang masih berlangsung. Dan ia… sedang ditarik ke dalamnya.",
        "Hingga pada suatu hari, langkahnya membawanya ke sebuah tempat yang tampak biasa. Sebuah bar. Tua. Sunyi. Namun saat ia melangkah masuk—Ia merasakannya. Bukan dari dinding. Bukan dari lantai. Melainkan dari seseorang. Seorang pria di balik meja. Tenang. Namun… kosong dengan cara yang tidak seharusnya dimiliki manusia.",
        "Franzsto mendekat. Dan untuk pertama kalinya sejak Arkaelia—Ia ragu. Karena ia tidak melihat masa lalu dari pria itu. Ia melihat… sesuatu yang lebih dalam. Seperti lubang. Seperti jurang yang menatap balik ke arahnya. “Menarik.” Pria itu berbicara lebih dulu. Seolah sudah menunggunya. “Jarang ada orang yang berjalan mengikuti jejak… bukan menghindarinya.”",
        "Franzsto menyipitkan mata. “Dan jarang ada tempat yang dipenuhi gema seperti ini.” Keheningan. Namun bukan keheningan biasa. Melainkan keheningan yang saling memahami. Pria itu tersenyum tipis. “Kalau begitu, kau sudah mendengar namanya.”",
        "Franzsto tidak menjawab. Namun tatapannya cukup. Eclipse Vow. Kata itu tidak perlu diucapkan. Pria itu meletakkan gelas di atas meja. Pelan. Seolah memberi tanda bahwa sesuatu… telah dimulai. “Frentzie.” Ia memperkenalkan diri. Bukan sebagai formalitas. Melainkan sebagai pengakuan. Bahwa percakapan ini… bukan kebetulan.",
        "Franzsto terdiam sejenak. Lalu bertanya— “Satu hal.” Tatapannya tajam. “Apakah kita menemukan sejarah… atau sejarah yang menemukan kita?” Frentzie tidak langsung menjawab. Ia hanya menatap balik. Dalam. Seolah menimbang sesuatu. Lalu akhirnya—”Jika kau masih bertanya itu…” Ia berhenti. Senyumnya tipis. “Hingga kini… kau masih belum cukup dalam.”",
        "Keheningan kembali turun. Namun kali ini—Bukan kosong. Melainkan penuh. Karena tanpa perlu kata-kata—Franzsto mengerti. Ia tidak lagi berjalan sendirian. Dan mungkin… Sejak awal… Ia memang tidak pernah berjalan sendiri."
    ];

    const sub3 = [
        "Dunia ini tidak pernah benar-benar tenang. Bagi sebagian orang, itu adalah kenyataan. Bagi Reinhard Tempest… itu adalah satu-satunya hal yang pernah ia kenal. Ia bukan pahlawan. Bukan legenda. Hanya seorang pengembara. Berjalan dari satu tempat ke tempat lain, tanpa tujuan yang pasti. Bukan karena ia mencari sesuatu—melainkan karena tidak ada tempat yang cukup aman untuk membuatnya berhenti.",
        "Padang yang ia lintasi selalu menyimpan bahaya. Hutan yang ia masuki selalu berbisik ancaman. Dan setiap langkah… selalu berpotensi menjadi yang terakhir. Busur sederhana di tangannya bukanlah simbol kehebatan. Melainkan alat untuk bertahan. Ia tidak memburu. Ia tidak mengejar kejayaan. Ia hanya… tidak ingin mati.",
        "Namun dunia tidak pernah puas hanya dengan itu. Suatu hari, langkahnya terhenti. Bukan karena ia memilih berhenti—Melainkan karena tubuhnya akhirnya menyerah. Luka. Lelah. Dan sesuatu yang lebih dalam dari sekadar rasa sakit fisik. Ia jatuh di tengah tanah tandus, di bawah langit yang terasa terlalu luas untuk seseorang yang sendirian. Suara monster mendekat. Pelan. Pasti.",
        "Reinhard mencoba bangkit. Namun tubuhnya tidak merespons. Untuk pertama kalinya… ia menyadari sesuatu. Mungkin, ini akhir. Namun sebelum kegelapan benar-benar menelannya—Sebuah suara terdengar. Ringan. Hampir tidak sesuai dengan situasi. “Wah, kelihatannya kamu lagi sial banget ya.”",
        "Langkah kecil. Cepat. Tanpa rasa takut. Seorang gadis dengan rambut hijau muncul di hadapannya. Senyumnya santai. Terlalu santai. Seolah monster yang mendekat hanyalah gangguan kecil. Yuffie. Di belakangnya, sosok lain berdiri. Diam. Namun kehadirannya… cukup untuk membuat udara terasa berbeda. Tatapan tajam. Gerakan yang siap meledak kapan saja. Steffy.",
        "Reinhard tidak sempat berkata apa-apa. Karena dalam sekejap—Pertarungan telah dimulai. Namun itu bukan pertarungan yang ia kenal. Tidak liar. Tidak panik. Melainkan… terarah. Steffy bergerak seperti bayangan yang memotong kegelapan. Cepat. Tepat. Sementara Yuffie—Ia tertawa kecil di tengah bahaya. Mengalihkan perhatian. Mengacaukan ritme. Sebuah kekacauan yang… disengaja.",
        "Dalam hitungan detik, semuanya berakhir. Sunyi kembali. Seolah tidak pernah terjadi apa-apa. Reinhard terdiam. Bukan karena takut. Melainkan karena ia menyadari sesuatu. Mereka… tidak bertarung untuk bertahan. Mereka bertarung untuk sesuatu yang lebih.",
        "Yuffie mendekat. Berjongkok di depannya. “Masih hidup, kan?” Nada suaranya ringan. Namun matanya… memperhatikan. Reinhard mengangguk pelan. Steffy tetap berdiri di belakang. Mengawasi. Menilai. Seolah memastikan bahwa orang yang mereka selamatkan… bukan ancaman. “Jarang ada yang bisa sampai sejauh ini sendirian,” kata Steffy akhirnya. Singkat. Datar. Namun tidak sepenuhnya dingin.",
        "Reinhard mencoba duduk. Sakitnya nyata. Namun ada sesuatu yang lebih kuat dari itu. Rasa asing. Bukan takut. Bukan curiga. Melainkan… hangat. Sesuatu yang sudah lama tidak ia rasakan. “Kenapa… kalian menolongku?” Pertanyaan itu keluar tanpa ia sadari. Yuffie tersenyum lebar. Seperti pertanyaan itu lucu. “Memangnya harus ada alasan?”",
        "Reinhard terdiam. Karena di dunia yang ia kenal—Selalu ada alasan. Namun Steffy melangkah mendekat. Tatapannya masih tajam. Namun kali ini… ada sesuatu yang berbeda. “Kalau kau ingin mati, itu pilihanmu.” Ia berhenti tepat di depan Reinhard. “Namun kalau kau masih ingin berjalan…” Sejenak, ia melirik ke arah Yuffie. Lalu kembali. “…jangan lakukan sendirian.”",
        "Keheningan. Namun bukan keheningan kosong. Melainkan keheningan yang memberi pilihan. Reinhard menatap mereka berdua. Dua sosok yang begitu berbeda… namun bergerak sebagai satu. Dan untuk pertama kalinya sejak lama—Ia tidak merasa sendirian.",
        "Ia menghela napas pelan. Lalu berkata, “Aku bukan orang kuat.” Yuffie tertawa kecil. “Bagus. Kita juga bukan pahlawan.” Steffy tidak tersenyum. Namun ia tidak menolak. Dan itu… cukup. Reinhard berdiri. Masih lemah. Namun kali ini—Tidak sendiri.", "Langkahnya mungkin belum pasti. Namun arahnya… mulai terbentuk. Dan di antara langkah-langkah itu, sebuah keyakinan perlahan tumbuh. Bahwa mungkin… Tidak semua yang bertahan adalah yang terkuat. Namun mereka yang memilih untuk tidak menyerah. Dan kali ini—Ia tidak berjalan sendirian."
    ];

    const sub4 = [
        "Ada orang-orang yang hancur karena dunia. Dan ada orang-orang… yang tetap hidup setelahnya. Chairil adalah salah satunya. Dulu, ia bukan siapa-siapa. Namun juga… bukan orang biasa. Sebagai bodyguard pribadi seseorang bernama Lyl, hidupnya diisi dengan satu tujuan sederhana—melindungi. Tanpa bertanya. Tanpa ragu. Ia adalah bayangan. Selalu ada… namun tidak pernah benar-benar terlihat. Dan dalam dunia seperti itu, ia belajar satu hal: Kesetiaan… selalu datang dengan harga.",
        "Namun semua itu berakhir. Bukan dengan pertempuran besar. Bukan dengan kematian yang heroik. Melainkan dengan keheningan. Ia pensiun. Menghilang dari dunia yang pernah membutuhkannya. Dan kembali… ke satu-satunya tempat yang ia sebut rumah. Kakak perempuannya. Satu-satunya keluarga yang tersisa.",
        "Bersamanya, Chairil mencoba membangun sesuatu yang berbeda. Bukan organisasi. Bukan kekuatan. Melainkan tempat. Komunitas kecil… yang ia beri nama Darkness. Sebuah ironi. Karena di dalamnya, untuk pertama kalinya, ia mencoba menciptakan sesuatu yang tidak gelap.",
        "Tiga tahun. Tiga tahun ia membangun. Mengumpulkan orang-orang yang tersisih. Yang terlupakan. Seperti dirinya. Dan untuk sesaat… ia percaya. Bahwa mungkin, hidup bisa menjadi lebih dari sekadar bertahan. Namun dunia… tidak pernah membiarkan sesuatu seperti itu bertahan lama. Komunitas itu hancur. Tidak jelas bagaimana. Tidak jelas kenapa. Seolah-olah sesuatu datang… dan menghapusnya. Dan lebih buruk dari itu—Kakaknya menghilang. Tanpa jejak. Tanpa jawaban. Hanya kekosongan yang tertinggal.",
        "Sejak saat itu, Chairil kembali menjadi bayangan. Namun kali ini… tanpa tujuan. Ia hidup. Namun tidak benar-benar menjalani hidup. Hari-harinya berlalu seperti orang biasa. Berjalan. Bernapas. Ada. Namun kosong. Hingga suatu hari, di pinggiran kota Sofya—Dengan kostum hijau yang terasa asing bahkan bagi dirinya sendiri—Ia bertemu mereka. Dua gadis berambut hijau. Steffy. Dan Yuffie.",
        "Ia langsung menyadari sesuatu. Bukan dari kata-kata. Melainkan dari cara mereka berdiri. Cara mereka mengamati. Cara mereka… tidak sepenuhnya menjadi bagian dari dunia ini. “Lucu juga,” kata Yuffie santai. “Jarang lihat orang pakai warna segini di tempat kayak gini.” Chairil tidak menjawab. Namun matanya tidak lepas dari mereka.",
        "Steffy melangkah sedikit ke depan. Tatapannya tajam. Mengukur. Menilai. “...kau bukan orang biasa.” Bukan pertanyaan. Pernyataan. Chairil terdiam sejenak. Lalu menjawab singkat, “Dan kalian juga bukan.” Keheningan singkat. Namun cukup untuk membentuk sesuatu. Sebuah pengertian tanpa perlu penjelasan.",
        "Namun pertemuan itu… bukan kebetulan. Karena seseorang telah menunggu. Dari balik bayangan kota—Seseorang melangkah mendekat. Tenang. Seolah semua ini… sudah ia rencanakan. Frentzie. Tatapannya langsung tertuju pada Chairil. Bukan ke wajahnya. Melainkan lebih dalam. Seperti melihat sesuatu yang tersembunyi. “Atau mungkin…” Ia berhenti sejenak. “…seseorang yang sudah terlalu lama mencoba menghilang.”",
        "Chairil tidak bereaksi. Namun untuk pertama kalinya—Ada sesuatu yang bergerak dalam dirinya. Frentzie melanjutkan. “Komunitas yang hancur. Kakak yang menghilang. Dan hidup yang kau jalani sekarang…” Ia menatap lurus. “…itu bukan kebetulan.” Udara terasa berat. Steffy terdiam. Yuffie tidak tersenyum kali ini.",
        "Chairil mengepalkan tangan. “Kalau kau tahu sesuatu…” Suaranya rendah. “…bicara.” Frentzie tersenyum tipis. Bukan senyum ramah. Melainkan senyum seseorang yang akhirnya menemukan bagian yang hilang. “Aku tidak tahu jawabannya.” Ia melangkah lebih dekat. “Namun aku tahu ke mana harus mencarinya.”",
        "Keheningan. Namun kali ini—Penuh dengan kemungkinan. “Bergabunglah.” Sederhana. Namun berat. “Kami mengumpulkan mereka yang tersisa.” Ia melirik Steffy dan Yuffie. Lalu kembali ke Chairil. “Vowbearer.” Kata itu… terasa asing. Namun juga… tidak sepenuhnya. Seolah ada bagian dari dirinya yang mengenalinya. Yang selama ini… terkubur.",
        "Chairil menunduk sejenak. Mengingat. Semua yang hilang. Semua yang hancur. Semua yang tidak pernah ia pahami. Lalu ia mengangkat kepalanya. Tatapannya kosong. Namun kali ini… ada arah. “Aku hanyalah manusia buangan…” Suaranya pelan. “…yang hancur dengan kesendirian yang menghantui setiap hidupku.” Ia berhenti. Lalu melangkah maju. “…jadi kalau memang ada jawaban di luar sana—” Tatapannya bertemu dengan Frentzie. “…aku akan menemukannya.”",
        "Frentzie tidak menjawab. Namun ia berbalik. Dan berjalan. Seperti biasa. Seolah tahu… bahwa mereka akan mengikuti. Dan di hari itu—Tanpa suara. Tanpa perayaan. Seorang penyintas lain… bergabung. Bukan sebagai pahlawan. Bukan sebagai penyelamat. Melainkan sebagai bagian dari sesuatu yang lebih besar. Sesuatu yang perlahan… mulai bangkit kembali."
    ];

    const sub5 = [
        "Tidak semua yang lahir… diizinkan untuk hidup. Beberapa hanya… ditunda kematiannya. Azuraa adalah salah satunya. Ia lahir dari seorang ibu yang bahkan dunia tidak pernah akui. Seorang budak pelarian. Seorang wanita yang hidupnya dihabiskan untuk bersembunyi—bukan dari sesuatu yang terlihat, tetapi dari sesuatu yang mengalir di dalam darahnya sendiri.",
        "Sebuah tanda. Bulan sabit… di punggungnya. Sebuah simbol yang tidak pernah dijelaskan. Namun selalu disembunyikan. Dengan lumpur. Dengan kain lusuh. Dengan ketakutan. Dan sejak kecil, Azuraa belajar satu hal tanpa pernah diajarkan: Ada sesuatu dalam dirinya… yang tidak boleh diketahui dunia.",
        "Namun dunia tidak pernah peduli pada rahasia kecil manusia. Ibunya mati. Bukan karena diburu. Bukan karena dibunuh. Melainkan karena lelah… bertahan hidup. Dan sejak saat itu, Azuraa benar-benar sendirian. Ia tumbuh di tempat yang bahkan tidak layak disebut kota. Oculum-Silent. Sebuah kota mati. Dipenuhi reruntuhan. Dipenuhi sisa energi. Dipenuhi… gema dari sesuatu yang telah lama hilang. Di sanalah ia hidup. Bukan sebagai manusia. Melainkan sebagai sesuatu yang bertahan. Mengais sisa kristal. Mengumpulkan energi yang bahkan tidak sepenuhnya ia pahami. Hari demi hari. Tanpa tujuan. Tanpa harapan.",
        "Hingga suatu hari—Dunia kembali mencoba mengambil segalanya darinya. Para penjarah. Mereka tidak datang untuk membunuh. Mereka datang untuk mengambil. Kalung tua. Satu-satunya peninggalan ibunya. Satu-satunya bukti… bahwa ia pernah dicintai. Azuraa menolak. Dan untuk itu—Ia dipukul. Dijatuhkan. Dihancurkan.",
        "Darahnya menyentuh tanah. Dan sesuatu… menjawab. Bukan pertolongan. Bukan keajaiban. Melainkan kebangkitan. Seluruh Oculum-Silent bergetar. Kristal-kristal yang mati… menyala. Udara yang kosong… beresonansi. Dan dalam sekejap—Para penjarah lenyap. Bukan terbunuh. Bukan melarikan diri. Melainkan… dihapus. Seolah mereka tidak pernah ada.",
        "Azuraa tidak mengerti. Namun ia merasakannya. Sesuatu dalam darahnya… telah bangkit. Eclipse Vow. Sebuah sumpah kuno. Sebuah warisan yang selama ini disembunyikan ibunya. Bukan untuk melindungi dunia. Melainkan… untuk melindunginya dari dunia. Sejak saat itu, Azuraa berubah. Ia tidak hanya merasakan dunia. Ia merasakan… emosi. Ketakutan. Kemarahaan. Kesedihan. Semuanya memiliki bentuk. Semuanya memiliki suara. Dan semuanya… bisa ia sentuh. Ia bisa menyerapnya. Menghancurkannya. Atau… mengembalikannya dalam bentuk yang lebih buruk. Ia menjadi sesuatu yang bahkan dunia pun tidak sepenuhnya pahami.",
        "Namun satu pertanyaan terus menghantuinya. Jika Tuhan benar-benar ada—Mengapa ibunya mati sendirian? Dan mengapa kekuatan ini… memilihnya? Bukan untuk menyelamatkan. Melainkan untuk bertahan. Dengan pertanyaan itu, Azuraa berjalan. Meninggalkan kota mati. Meninggalkan sisa dirinya yang lama. Menuju sesuatu yang belum ia mengerti. Namun takdir… tidak pernah membiarkan seseorang seperti dirinya berjalan terlalu jauh sendirian.",
        "Langkahnya akhirnya terhenti. Bukan karena ia lelah. Melainkan karena ia merasakan sesuatu. Emosi. Tiga. Berbeda. Namun terhubung. Satu… dingin seperti pisau. Satu… ringan seperti tawa. Dan satu lagi… kosong. Kosong dengan cara yang menyesakkan. Azuraa tidak bersembunyi. Ia tidak lari. Ia menunggu. Dan mereka datang. Steffy. Yuffie. Dan Chairil.",
        "Pertemuan itu tidak dimulai dengan kata-kata. Melainkan dengan rasa. Yuffie adalah yang pertama berbicara. “Wah…” Senyumnya melebar. “…ini pertama kalinya aku ngerasa sesuatu kayak gini.” Namun kali ini, nada suaranya tidak sepenuhnya bercanda. Steffy melangkah sedikit ke depan. Tatapannya tajam. Namun tidak menyerang. Mengukur. Selalu mengukur. “Dia berbahaya.” Singkat. Jelas.",
        "Chairil tidak langsung bereaksi. Namun matanya… tidak lepas dari Azuraa. Karena ia merasakan sesuatu yang familiar. Kehilangan. Kesendirian. Dan sesuatu yang lebih dalam dari itu. Azuraa memiringkan kepalanya sedikit. Menatap mereka bertiga. “Atau mungkin…” Suaranya tenang. Namun berat. “…kalian yang terlalu rapuh untuk memahami.” Udara berubah. Emosi mulai bergetar. Tak terlihat. Namun terasa.",
        "Yuffie mengangkat tangan. “Eh, santai dulu.” Ia tertawa kecil. “Kalau mau hancurin kita, nanti aja. Kenalan dulu gimana?” Steffy tidak menurunkan kewaspadaannya. Namun ia tidak menyerang. Karena ia tahu. Jika gadis ini ingin… Pertarungan tidak akan terjadi. Hanya… akhir.",
        "Chairil akhirnya melangkah maju. Pelan. Tidak mengancam. Namun tidak juga lemah. “Aku pernah lihat orang yang kehilangan segalanya.” Suaranya rendah. “…dan aku tahu tatapan itu.” Azuraa terdiam. Untuk pertama kalinya—Emosi di sekitarnya… bergetar. Bukan karena kekuatannya. Melainkan karena sesuatu yang lebih manusiawi. “Kalau kau mencari jawaban…” Chairil melanjutkan. “…kami juga.” Keheningan. Namun kali ini—Tidak kosong.",
        "Yuffie tersenyum. Lebih lembut dari sebelumnya. “Dan jujur aja…” Ia mengangkat bahu. “…kita semua kelihatan kayak masalah berjalan.” Sedikit tawa. Kecil. Namun cukup untuk memecah ketegangan. Steffy menatap Azuraa. Dalam. Seolah mencari sesuatu. Atau memastikan. “Kalau kau tetap sendiri…” Ia berkata pelan. “…dunia ini tidak akan memberimu jawaban.”",
        "Azuraa menutup matanya sejenak. Merasakan. Emosi mereka. Tidak sempurna. Tidak bersih. Namun… nyata. Berbeda dari dunia yang ia kenal. Ia membuka matanya. Tatapannya masih dalam. Namun kini… ada arah. “Dunia melihatku sebagai budak…” Suaranya pelan. “…tapi takdir melihatku sebagai sesuatu yang lain.” Ia melangkah maju. Perlahan. Menuju mereka. “Aku tidak mencari kekuasaan.” Tatapannya bertemu dengan mereka bertiga. “…aku hanya ingin tahu… kenapa aku tidak dibiarkan mati.”",
        "Keheningan. Namun kali ini—Tidak ada penolakan. Tidak ada penolakan… sama sekali. Dan di antara empat jiwa yang rusak—Sesuatu terbentuk. Bukan kepercayaan. Belum. Namun cukup… untuk berjalan bersama. Menuju sesuatu yang lebih besar. Sesuatu yang perlahan… mulai memanggil mereka semua."
    ];

    if (sub_chapters[0]) sub_chapters[0].content = sub0;
    if (sub_chapters[1]) sub_chapters[1].content = sub1;
    if (sub_chapters[2]) sub_chapters[2].content = sub2;
    if (sub_chapters[3]) sub_chapters[3].content = sub3;
    if (sub_chapters[4]) sub_chapters[4].content = sub4;
    if (sub_chapters[5]) sub_chapters[5].content = sub5;
    // sub 6 is Caeliraa, it is already good
  }

  fs.writeFileSync(storyPath, JSON.stringify(data, null, 2));
  console.log('Successfully formatted story.json paragraphs!');
} catch (e) {
  console.error('Error:', e);
}
